services:
  db:
    image: mysql:8.0.40-debian
    container_name: frutt_db
    #restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - frutt-network
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: frutt_api
    env_file:
      - .env
    depends_on: # junto ao `healthcheck` do `db`, garante que `api` so rode quando banco estiver up
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - frutt-network

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - api
  #   ports:
  #     - 80:80
  #   networks:
  #     - frutt-network
  #   volumes:
  #     - web:/var/www/html


networks:
  frutt-network:
    driver: bridge

volumes:
  db:
  # web: